databases:
  - name: postgres
    databaseName: tasty_trek_db
    user: kenneth

services:
  - type: web
    name: recipe
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tasty_trek_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false