databases:
  - name: postgres
    databaseName: tasty_trek_production
    user: 

services:
  - type: web
    name: tasty_trek
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tasty_trek_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
